remove debug and update cmd

diff --git a/.github/actions/kibana-ftr/action.yml b/.github/actions/kibana-ftr/action.yml
--- a/.github/actions/kibana-ftr/action.yml
+++ b/.github/actions/kibana-ftr/action.yml
@@ -43,12 +43,14 @@ runs:
       working-directory: ${{ steps.globals.outputs.KIBANA_DIR }}
       run: |
         echo "Bootstrapping Kibana..."
+        yarn kbn bootstrap --force-install --no-validation || echo "⚠️ yarn kbn bootstrap failed, continuing..."
+        yarn kbn clean && yarn kbn reset || echo "⚠️ yarn kbn reset failed, continuing..."
         yarn kbn bootstrap
-      
+
     # TODO: Remove after debugging
-    - name: Setup tmate session
-      uses: mxschmitt/action-tmate@v3
-      if: failure()
+    # - name: Setup tmate session
+    #   uses: mxschmitt/action-tmate@v3
+    #   if: failure()
 
     - name: Set TEST_CLOUD_HOST_NAME
       shell: bash
