add ability to destroy environments in qa

diff --git a/.github/workflows/destroy-environment.yml b/.github/workflows/destroy-environment.yml
--- a/.github/workflows/destroy-environment.yml
+++ b/.github/workflows/destroy-environment.yml
@@ -32,6 +32,7 @@ env:
   ENV_PREFIX: ${{ inputs.prefix }}
   ENV_IGNORE_PREFIX: ${{ inputs.ignore-prefix }}
   TF_VAR_ec_api_key: ${{ secrets.EC_API_KEY }}
+  TF_VAR_qa_ec_api_key: ${{ secrets.QA_EC_API_KEY }}
 
 jobs:
   Destroy:
@@ -50,13 +51,30 @@ jobs:
         working-directory: ./
 
       - name: Mask API Key
-        if: ${{ inputs.ec-api-key != '' }}
-        run: |
+        run:
+          |
+          # Extract the EC API key and selected EC URL
+          input_ec_url="${{ inputs.ec-url }}"
           ec_api_key=$(jq -r '.inputs["ec-api-key"]' $GITHUB_EVENT_PATH)
-          ec_url=$(jq -r '.inputs["ec-url"]' $GITHUB_EVENT_PATH)
-          echo "::add-mask::$ec_api_key"
-          echo "TF_VAR_ec_api_key=$ec_api_key" >> $GITHUB_ENV
-          echo "TF_VAR_ec_url=$ec_url" >> $GITHUB_ENV
+
+          # Production elastic cloud url
+          ec_url="${{ env.PROD_EC_URL }}"
+
+          # QA elastic cloud url
+          qa_ec_url="${{ env.QA_EC_URL }}"
+
+          # Handles setting API KEY for each deployment mode for  elastic cloud  environment
+          if [[ $ec_api_key != '' && $input_ec_url == $ec_url ]]; then
+            echo "::add-mask::$ec_api_key"
+            echo "TF_VAR_ec_api_key=$ec_api_key" >> $GITHUB_ENV
+          elif [[ $input_ec_url == $ec_url ]]; then
+            echo "TF_VAR_ec_api_key=$TF_VAR_ec_api_key" >> $GITHUB_ENV
+          elif [[ $input_ec_url == $qa_ec_url ]]; then
+            echo "TF_VAR_ec_api_key=$TF_VAR_qa_ec_api_key" >> $GITHUB_ENV
+          else
+            echo "error: Elastic Cloud API key igis required from a valid ec url"
+            exit 1
+          fi
 
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v2
