k8s

diff --git a/.github/workflows/pr-ci.yml b/.github/workflows/pr-ci.yml
--- a/.github/workflows/pr-ci.yml
+++ b/.github/workflows/pr-ci.yml
@@ -12,6 +12,10 @@ on:
       - "[0-9]+.[0-9]+"
   workflow_dispatch:
 
+concurrency:
+  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
+  cancel-in-progress: true
+
 jobs:
   init-hermit:
     name: Init Hermit Tools
@@ -22,6 +26,83 @@ jobs:
         uses: actions/checkout@v4
       - name: Hermit Environment
         uses: ./.github/actions/hermit
+
+  lint:
+    needs: [ init-hermit ]
+    name: Lint
+    runs-on: ubuntu-22.04
+    timeout-minutes: 60
+    steps:
+      - name: Check out the repo
+        uses: actions/checkout@v4
+
+      - name: Hermit Environment
+        uses: ./.github/actions/hermit
+
+      - name: Pre-commit Hooks
+        env:
+          # Skipping golangci-lint as it's tested by golangci-lint
+          SKIP: golangci-lint
+        shell: bash
+        run: |
+          pre-commit run --all-files
+
+      - name: golangci-lint
+        shell: bash
+        run: golangci-lint run --out-format github-actions
+
+      - name: Mage Check
+        shell: bash
+        run: mage check
+
+      - name: Mage checkLicenseHeaders
+        shell: bash
+        run: mage checkLicenseHeaders
+
+      - name: Validate mocks
+        shell: bash
+        run: just validate-mocks
+
+      - name: Terraform fmt
+        shell: bash
+        run: terraform fmt -check -recursive
+
+  unit-test:
+    needs: [ init-hermit ]
+    name: Unit Test
+    runs-on: ubuntu-22.04
+    timeout-minutes: 60
+    steps:
+      - name: Check out the repo
+        uses: actions/checkout@v4
+
+      - name: Hermit Environment
+        uses: ./.github/actions/hermit
+
+      - name: Build opa bundle
+        shell: bash
+        run: mage buildOpaBundle
+
+      - name: Unit-Test
+        shell: bash
+        run: |
+          go install gotest.tools/gotestsum
+          GOOS=linux TEST_DIRECTORY=./... gotestsum --format pkgname -- -race -coverpkg=./... -coverprofile=cover.out.tmp
+          cat cover.out.tmp | grep -v "mock_.*.go" > cover.out # remove mock files from coverage report
+
+      - name: Upload coverage artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: coverage-file
+          path: cover.out
+
+      - name: Send coverage
+        env:
+          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        shell: bash
+        run: |
+          go install github.com/mattn/goveralls@latest
+          goveralls -coverprofile=cover.out -service=github
 
   ci-azure:
     needs: [ init-hermit ]
@@ -113,52 +194,115 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: 'us-east-2'
 
+  docker-images:
+    needs: [ init-hermit ]
+    name: Build docker images
+    # Since we build the cloudbeat in the worker's OS and as non static,
+    # we need to keep the OS version same as elastic-agent docker image base.
+    # docker run --interactive --tty --rm --entrypoint bash docker.elastic.co/elastic-agent/elastic-agent-complete:8.14.0-SNAPSHOT -c 'cat /etc/os-release'
+    runs-on: ubuntu-20.04
+    timeout-minutes: 40
+    env:
+      CONTAINER_SUFFIX: ${{ github.run_id }}
+      CI_ELASTIC_AGENT_DOCKER_TAG: "8.14.0-SNAPSHOT"
+      CI_ELASTIC_AGENT_DOCKER_IMAGE: "704479110758.dkr.ecr.eu-west-2.amazonaws.com/elastic-agent"
+    steps:
+      - name: Check out the repo
+        uses: actions/checkout@v4
+
+      - name: Hermit Environment
+        uses: ./.github/actions/hermit
+
+      - name: Build docker images
+        uses: ./.github/actions/docker-images
+        with:
+          elk-version: ${{ env.ELK_VERSION }}
+          container-image-suffix: ${{ github.run_id }}
+          elastic-agent-docker-image: ${{ env.CI_ELASTIC_AGENT_DOCKER_IMAGE }}
+          elastic-agent-docker-image-tag: ${{ env.CI_ELASTIC_AGENT_DOCKER_TAG }}
+
+  ci-k8s:
+    needs: [ init-hermit, docker-images ]
+    name: ${{ matrix.test-target }}-${{ matrix.kind-config }}
+    runs-on: ubuntu-22.04
+    timeout-minutes: 120
+    strategy:
+      fail-fast: false
+      matrix:
+        include:
+          - test-target: pre_merge
+            kind-config: kind-multi
+            values-file: tests/test_environments/values/ci.yml
+          - test-target: pre_merge_agent
+            kind-config: kind-multi
+            values-file: tests/test_environments/values/ci-sa-agent.yml
+          - test-target: k8s_file_system_rules
+            kind-config: kind-test-files
+            values-file: tests/test_environments/values/ci-test-k8s-files.yml
+          - test-target: k8s_object_psp_rules
+            kind-config: kind-multi
+            values-file: tests/test_environments/values/ci-test-k8s-objects.yml
+          - test-target: k8s_process_rules
+            kind-config: kind-test-proc-conf1
+            values-file: tests/test_environments/values/ci-test-k8s-proc-conf1.yml
+          - test-target: k8s_process_rules
+            kind-config: kind-test-proc-conf2
+            values-file: tests/test_environments/values/ci-test-k8s-proc-conf2.yml
+    env:
+      CONTAINER_SUFFIX: ${{ github.run_id }}
+      CI_ELASTIC_AGENT_DOCKER_TAG: "8.14.0-SNAPSHOT"
+      CI_ELASTIC_AGENT_DOCKER_IMAGE: "704479110758.dkr.ecr.eu-west-2.amazonaws.com/elastic-agent"
+    steps:
+      - name: Check out the repo
+        uses: actions/checkout@v4
+
+      - name: Hermit Environment
+        uses: ./.github/actions/hermit
+
+      - name: Run k8s integration tests
+        uses: ./.github/actions/k8s-ci
+        with:
+          elk-version: ${{ env.ELK_VERSION }}
+          kind-config: ${{ matrix.kind-config }}
+          container-image-suffix: ${{ github.run_id }}
+          elastic-agent-docker-image: ${{ env.CI_ELASTIC_AGENT_DOCKER_IMAGE }}
+          elastic-agent-docker-image-tag: ${{ env.CI_ELASTIC_AGENT_DOCKER_TAG }}
+          test-target: ${{ matrix.test-target }}
+          values-file: ${{ matrix.values-file }}
+
+      # - name: Setup tmate session
+      #   uses: mxschmitt/action-tmate@v3
+      #   if: failure()
+      #   with:
+      #     limit-access-to-actor: true
+
   upload-allure-results:
     needs:
       - ci-azure
       - ci-aws
       - ci-gcp
       - ci-cnvm
+      - ci-k8s
     name: Upload integration tests results
     runs-on: ubuntu-22.04
     timeout-minutes: 60
-    if: always()
+    if: ${{ success() || failure() }}
     steps:
       - uses: actions/download-artifact@v4
-        if: always()
+        if: ${{ success() || failure() }}
         with:
-          name: allure-results-ci-azure
-          path: tests/allure/results/
-          merge-multiple: true
-
-      - uses: actions/download-artifact@v4
-        if: always()
-        with:
-          name: allure-results-ci-aws
-          path: tests/allure/results/
-          merge-multiple: true
-
-      - uses: actions/download-artifact@v4
-        if: always()
-        with:
-          name: allure-results-ci-gcp
-          path: tests/allure/results/
-          merge-multiple: true
-
-      - uses: actions/download-artifact@v4
-        if: always()
-        with:
-          name: allure-results-ci-cnvm
           path: tests/allure/results/
           merge-multiple: true
 
       - name: log
-        if: always()
+        if: ${{ success() || failure() }}
         shell: bash
-        run: ls -laR
+        run: |
+          ls -lahR || true
+          rm -f tests/allure/results/cover.out || true
 
       - name: Publish allure report
-        if: always()
+        if: ${{ success() || failure() }}
         uses: andrcuns/allure-publish-action@v2.6.0
         env:
           GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
