remove keep prefix  and update api key logic

diff --git a/.github/workflows/test-environment.yml b/.github/workflows/test-environment.yml
--- a/.github/workflows/test-environment.yml
+++ b/.github/workflows/test-environment.yml
@@ -158,8 +158,8 @@ jobs:
           fi
 
           # Check pattern required for cloud deployment
-          if ! [[ $deployment_name =~ (^keep_[a-z][-a-z0-9]*|[a-z][-a-z0-9]*)$ ]]; then
-            echo "error: Deployment name doesn't match the required pattern QA env keep_[a-z][-a-z0-9]* or regular env [a-z][-a-z0-9]*"
+          if ! [[ $deployment_name =~ ([a-z][-a-z0-9]*)$ ]]; then
+            echo "error: Deployment name doesn't match the required pattern regular env [a-z][-a-z0-9]*"
             exit 1
           fi
 
@@ -177,7 +177,7 @@ jobs:
           ec_url="${{ env.EC_URL }}"
 
           # When user stores input ec api key then update Elastic Cloud env API KEY
-          if [[ $ec_api_key != '' && $input_ec_url == $ec_url ]]; then
+          if [[ $ec_api_key != '' ]]; then
             echo "::add-mask::$ec_api_key"
             echo "TF_VAR_ec_api_key=$ec_api_key" >> $GITHUB_ENV
           elif [[ $input_ec_url == $ec_url ]]; then
