fix spacing for syntax

diff --git a/.github/workflows/test-environment.yml b/.github/workflows/test-environment.yml
--- a/.github/workflows/test-environment.yml
+++ b/.github/workflows/test-environment.yml
@@ -178,7 +178,7 @@ jobs:
           ec_url="${{ env.EC_URL }}"
 
           # When user stores input ec api key then update Elastic Cloud env API KEY
-          if [[ $ec_api_key != '' && $input_ec_url == $ec_url]]; then
+          if [[ $ec_api_key != '' && $input_ec_url == $ec_url ]]; then
             echo "::add-mask::$ec_api_key"
             echo "TF_VAR_ec_api_key=$ec_api_key" >> $GITHUB_ENV
           elif [[ $input_ec_url == $ec_url && $ec_api_key == '' ]]; then
@@ -186,8 +186,8 @@ jobs:
           elif [[ $input_ec_url == $qa_ec_url ]]; then
             echo "TF_VAR_ec_api_key=${local_qa_ec_api_key}" >> $GITHUB_ENV
           else
-              echo "error: Elastic Cloud API key is required from a valid ec url"
-              exit 1
+            echo "error: Elastic Cloud API key is required from a valid ec url"
+            exit 1
           fi
 
       - name: Process Stack Version
