fix exit strategy

diff --git a/.github/workflows/test-environment.yml b/.github/workflows/test-environment.yml
--- a/.github/workflows/test-environment.yml
+++ b/.github/workflows/test-environment.yml
@@ -112,6 +112,7 @@ env:
   GCP_DEFAULT_TAGS: "division=engineering,org=security,team=cloud-security-posture,project=test-environments"
   TF_VAR_ec_api_key: ${{ secrets.EC_API_KEY }}
   TF_VAR_qa_ec_api_key: ${{ secrets.QA_EC_API_KEY }}
+  TF_VAR_ec_url: ${{ inputs.ec-url }}
 
 
 jobs:
@@ -130,7 +131,6 @@ jobs:
       S3_BUCKET_URL: "https://s3.console.aws.amazon.com/s3/buckets/tf-state-bucket-test-infra"
       DOCKER_IMAGE_OVERRIDE: ${{ inputs.docker-image-override }}
       CNVM_STACK_NAME: "${{ inputs.deployment_name }}-cnvm-sanity-test-stack"
-      TF_VAR_ec_url: ${{ inputs.ec-url }}
     # Add "id-token" with the intended permissions.
     permissions:
       contents: "read"
@@ -179,14 +179,13 @@ jobs:
           if [[ $ec_api_key != '' ]]; then
             echo "::add-mask::$ec_api_key"
             echo "TF_VAR_ec_api_key=$ec_api_key" >> $GITHUB_ENV
-            exit 0
-          fi
-
-          if [[ $input_ec_url == $qa_ec_url ]]; then
-            echo "TF_VAR_ec_api_key=$TF_VAR_qa_ec_api_key" >> $GITHUB_ENV
           else
-            echo "error: Elastic Cloud API key is required from a valid ec url"
-            exit 1
+            if [[ $input_ec_url == $qa_ec_url ]]; then
+              echo "TF_VAR_ec_api_key=$TF_VAR_qa_ec_api_key" >> $GITHUB_ENV
+            else
+              echo "error: Elastic Cloud API key is required from a valid ec url"
+              exit 1
+            fi
           fi
 
       - name: Process Stack Version
